### PR TITLE
support python3 and AtCoder

### PR DESCRIPTION
**Pull request by kotapiku**
This support python3 and implement atcoder mode (and support macOS).
This cannot build by python2. If you admit this demerit, please merge it.

### CODE REVIEW

**Comment by coderick14** [comment]
Hey. I'm running a bit busy. I'll take a look at your changes within a couple of days. And thanks for the contribution!! Support for `AtCoder` is a really good feature.

**Comment by coderick14** [comment]
Hey.

I tried setting up your code. Installation works *smoothly*. :+1: 
Then I tried running the following command
```
acedit -s atcoder -c abc089 -p abc089_a
```
It said `Done`. But the cache directory for that problem was still empty. Can you look into it, please?

**Comment by kotapiku** [comment]
Sorry, I modified the problem (url was wrong when download specify problem).
Please check it.

**Comment by coderick14** [comment]
There are a few minor things I changed, which are in a new branch. I'll be merging the changes soon. I've squashed multiple commits into a single one. Thanks a lot for your help @kotapiku 

I've added your name as a contributor to the README. Thanks again!

**Comment by kotapiku** [comment]
I’m sorry for overlooking some your mail.
Thank you very much!

kotapiku
2019年5月31日 21:14 +0900、Deep Bhattacharyya のメール:

**Pull request closed without merging**
